let mineralsData = [
    {
        name: 'Нефть',
        aggregation: 'Жидкое',
        density: '0.85',
        thermal_conductivity: '0.15',
        electrical_conductivity: '0.001',
        flammability: 'Горючее',
        country: 'Саудовская Аравия',
    },
    {
        name: 'Природный газ',
        aggregation: 'Газообразное',
        density: '0.0008',
        thermal_conductivity: '0.03',
        electrical_conductivity: '0.0006',
        flammability: 'Горючее',
        country: 'Россия',
    },
    {
        name: 'Уголь',
        aggregation: 'Твердое',
        density: '1.3',
        thermal_conductivity: '0.20',
        electrical_conductivity: '0.0001',
        flammability: 'Горючее',
        country: 'Китай',
    },
    {
        name: 'Железная руда',
        aggregation: 'Твердое',
        density: '5.0',
        thermal_conductivity: '80',
        electrical_conductivity: '1.0',
        flammability: 'Негорючее',
        country: 'Австралия',
    },
    {
        name: 'Медь',
        aggregation: 'Твердое',
        density: '8.96',
        thermal_conductivity: '400',
        electrical_conductivity: '5.96',
        flammability: 'Негорючее',
        country: 'Чили',
    },
    {
        name: 'Золото',
        aggregation: 'Твердое',
        density: '19.3',
        thermal_conductivity: '318',
        electrical_conductivity: '45.2',
        flammability: 'Негорючее',
        country: 'Канада',
    },
    {
        name: 'Алмаз',
        aggregation: 'Твердое',
        density: '3.51',
        thermal_conductivity: '1000',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Ботсвана',
    },
    {
        name: 'Платина',
        aggregation: 'Твердое',
        density: '21.45',
        thermal_conductivity: '72',
        electrical_conductivity: '10',
        flammability: 'Негорючее',
        country: 'Россия',
    },
    {
        name: 'Никель',
        aggregation: 'Твердое',
        density: '8.9',
        thermal_conductivity: '90',
        electrical_conductivity: '14.3',
        flammability: 'Негорючее',
        country: 'Филиппины',
    },
    {
        name: 'Свинец',
        aggregation: 'Твердое',
        density: '11.34',
        thermal_conductivity: '35',
        electrical_conductivity: '4.8',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Боксит',
        aggregation: 'Твердое',
        density: '2.55',
        thermal_conductivity: '30',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Австралия',
    },
    {
        name: 'Алюминий',
        aggregation: 'Твердое',
        density: '2.7',
        thermal_conductivity: '235',
        electrical_conductivity: '3.77',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Уран',
        aggregation: 'Твердое',
        density: '18.95',
        thermal_conductivity: '27',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Казахстан',
    },
    {
        name: 'Сера',
        aggregation: 'Твердое',
        density: '2.07',
        thermal_conductivity: '0.205',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'США',
    },
    {
        name: 'Цинк',
        aggregation: 'Твердое',
        density: '7.14',
        thermal_conductivity: '116',
        electrical_conductivity: '1.7',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Титан',
        aggregation: 'Твердое',
        density: '4.51',
        thermal_conductivity: '22',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Австралия',
    },
    {
        name: 'Олово',
        aggregation: 'Твердое',
        density: '7.28',
        thermal_conductivity: '67',
        electrical_conductivity: '9.17',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Кобальт',
        aggregation: 'Твердое',
        density: '8.9',
        thermal_conductivity: '100',
        electrical_conductivity: '6.7',
        flammability: 'Негорючее',
        country: 'Конго',
    },
    {
        name: 'Гранит',
        aggregation: 'Твердое',
        density: '2.75',
        thermal_conductivity: '1.7',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Индия',
    },
    {
        name: 'Мрамор',
        aggregation: 'Твердое',
        density: '2.71',
        thermal_conductivity: '2.1',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Италия',
    },
    {
        name: 'Глина',
        aggregation: 'Твердое',
        density: '1.6',
        thermal_conductivity: '0.25',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Песок',
        aggregation: 'Твердое',
        density: '1.6',
        thermal_conductivity: '0.33',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'США',
    },
    {
        name: 'Фосфорит',
        aggregation: 'Твердое',
        density: '2.8',
        thermal_conductivity: '0',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Марокко',
    },
    {
        name: 'Вольфрам',
        aggregation: 'Твердое',
        density: '19.3',
        thermal_conductivity: '170',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Калийная соль',
        aggregation: 'Твердое',
        density: '2.0',
        thermal_conductivity: '0',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Канада',
    },
    {
        name: 'Известняк',
        aggregation: 'Твердое',
        density: '2.7',
        thermal_conductivity: '1.26',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'США',
    },
    {
        name: 'Цирконий',
        aggregation: 'Твердое',
        density: '6.52',
        thermal_conductivity: '22',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Австралия',
    },
    {
        name: 'Магний',
        aggregation: 'Твердое',
        density: '1.74',
        thermal_conductivity: '160',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Кварц',
        aggregation: 'Твердое',
        density: '2.65',
        thermal_conductivity: '1.3',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Бразилия',
    },
    {
        name: 'Ртуть',
        aggregation: 'Жидкое',
        density: '13.53',
        thermal_conductivity: '8.34',
        electrical_conductivity: '1',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Калий',
        aggregation: 'Твердое',
        density: '0.86',
        thermal_conductivity: '102.4',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Канада',
    },
    {
        name: 'Селен',
        aggregation: 'Твердое',
        density: '4.81',
        thermal_conductivity: '0.5',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Барит',
        aggregation: 'Твердое',
        density: '4.5',
        thermal_conductivity: '1.3',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Флюорит',
        aggregation: 'Твердое',
        density: '3.18',
        thermal_conductivity: '1.1',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Гипс',
        aggregation: 'Твердое',
        density: '2.32',
        thermal_conductivity: '1.0',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'США',
    },
    {
        name: 'Слюда',
        aggregation: 'Твердое',
        density: '2.8',
        thermal_conductivity: '0.52',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Индия',
    },
    {
        name: 'Бор',
        aggregation: 'Твердое',
        density: '2.34',
        thermal_conductivity: '27',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Турция',
    },
    {
        name: 'Ильменит',
        aggregation: 'Твердое',
        density: '4.7',
        thermal_conductivity: '10',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Австралия',
    },
    {
        name: 'Молибден',
        aggregation: 'Твердое',
        density: '10.2',
        thermal_conductivity: '138',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Рений',
        aggregation: 'Твердое',
        density: '21.02',
        thermal_conductivity: '48',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Чили',
    },
    {
        name: 'Галлий',
        aggregation: 'Твердое',
        density: '5.91',
        thermal_conductivity: '29.4',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Литий',
        aggregation: 'Твердое',
        density: '0.53',
        thermal_conductivity: '84.8',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Австралия',
    },
    {
        name: 'Гематит',
        aggregation: 'Твердое',
        density: '5.26',
        thermal_conductivity: '11',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Бразилия',
    },
    {
        name: 'Пирит',
        aggregation: 'Твердое',
        density: '5.01',
        thermal_conductivity: '30',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Испания',
    },
    {
        name: 'Халькопирит',
        aggregation: 'Твердое',
        density: '4.2',
        thermal_conductivity: '17',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Канада',
    },
    {
        name: 'Киноварь',
        aggregation: 'Твердое',
        density: '8.1',
        thermal_conductivity: '0.2',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Китай',
    },
    {
        name: 'Магнит',
        aggregation: 'Твердое',
        density: '5.2',
        thermal_conductivity: '5.2',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Россия',
    },
    {
        name: 'Кальцит',
        aggregation: 'Твердое',
        density: '2.71',
        thermal_conductivity: '3.59',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'США',
    },
    {
        name: 'Азурит',
        aggregation: 'Твердое',
        density: '3.77',
        thermal_conductivity: '0',
        electrical_conductivity: '0',
        flammability: 'Негорючее',
        country: 'Марокко',
    },
];